### ISSUE TITLE
White screen

### ISSUE THREAD

**Issue by mmUser123** [paviro/MMM-FRITZ-Box-Callmonitor#12] opened 2016-08-28 09:32 UTC
After the installation process the MagicMirror-Monitor (not call monitor itself) is completely white.
I use the newest MagicMirror.

```
                {
                        module: 'MMM-FRITZ-Box-Callmonitor',
                        position: 'top_left',
                        header: 'Calls',
                        config: {
                                fritzIP: 'x.x.x.x'
                        }
                }
```

```
drwxr-xr-x  5 pi pi  4096 Aug 28 11:08 .
drwxr-xr-x 14 pi pi  4096 Aug 27 22:48 ..
drwxr-xr-x 10 pi pi  4096 Aug 27 22:10 default
drwxr-xr-x  4 pi pi  4096 Aug 28 11:08 MMM-FRITZ-Box-Callmonitor
drwxr-xr-x  3 pi pi  4096 Aug 28 11:23 node_modules
-rw-r--r--  1 pi pi 22719 Aug 27 22:10 README.md
```

**Comment by Jopyth** [comment] 2016-09-16 19:50
I think I know what the problem is. Are you trying to read your contacts from a VCF file?

**Comment by paviro** [comment] 2016-12-11 15:49
I close this for now, feel free to reopen :)

**Closed by paviro** 2016-12-11 15:49 UTC
